SGT Back-End - AT
ameliatalkington/c0121-code-solutions pull request #106
Opened 2021-03-19 23:45 UTC by ameliatalkington

<img width="614" alt="Screen Shot 2021-03-19 at 4 42 12 PM" src="https://user-images.githubusercontent.com/52344883/111851927-642b4880-88d2-11eb-9b60-53209c29899c.png">
<img width="717" alt="Screen Shot 2021-03-19 at 4 42 36 PM" src="https://user-images.githubusercontent.com/52344883/111851929-655c7580-88d2-11eb-8419-cf40bf4264e7.png">
<img width="698" alt="Screen Shot 2021-03-19 at 4 42 44 PM" src="https://user-images.githubusercontent.com/52344883/111851932-668da280-88d2-11eb-9c17-e1b824758a0b.png">
<img width="723" alt="Screen Shot 2021-03-19 at 4 42 59 PM" src="https://user-images.githubusercontent.com/52344883/111851935-67becf80-88d2-11eb-9d8d-fcd68efc13d9.png">
<img width="693" alt="Screen Shot 2021-03-19 at 4 43 24 PM" src="https://user-images.githubusercontent.com/52344883/111851939-69889300-88d2-11eb-8341-974dcc62bd7d.png">
<img width="736" alt="Screen Shot 2021-03-19 at 4 43 31 PM" src="https://user-images.githubusercontent.com/52344883/111851941-6ab9c000-88d2-11eb-8a2e-520c0dcaeddc.png">

2021-03-19 23:47 UTC, thebearingedge requested changes

2021-03-19 23:47 UTC, thebearingedge commented on sgt-back-end/index.js
> +  `;
You can include a `returning` clause in your `delete` statement so you don't have to query the database twice.

2021-03-20 00:07 UTC, ameliatalkington commented
<img width="587" alt="Screen Shot 2021-03-19 at 5 06 15 PM" src="https://user-images.githubusercontent.com/52344883/111852814-a6a25480-88d5-11eb-9208-d8bb813c7d5f.png">

2021-03-20 00:15 UTC, thebearingedge approved these changes

2021-03-25 01:47 UTC, merged