Completed CSS Brochure Form - Amelia Talkington
ameliatalkington/c0121-code-solutions pull request #15
Opened 2021-01-21 01:51 UTC by ameliatalkington

<img width="417" alt="Screen Shot 2021-01-20 at 6 40 21 PM" src="https://user-images.githubusercontent.com/52344883/105269032-6bdba480-5b50-11eb-82dd-d8a44abba9d7.png">

2021-01-21 20:43 UTC, codingcodymiller requested changes
Hey Amelia! Please see my notes:

2021-01-21 20:43 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
You can remove this.

2021-01-21 20:43 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  font-size: medium;
Stick with `rem` for font sizes, if possible.

2021-01-21 20:43 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  font-size: x-small;
Stick with `rem` for font sizes, if possible.

2021-01-21 20:43 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  padding-left: 2%;
Stick with `px` or `rem` for padding, if possible

2021-01-21 20:43 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  font-size: small;
Stick with `rem` for font sizes, if possible

2021-01-21 21:06 UTC, ameliatalkington commented
<img width="466" alt="Screen Shot 2021-01-21 at 2 02 37 PM" src="https://user-images.githubusercontent.com/52344883/105412314-ce38b180-5bf1-11eb-9b51-7de108726ba1.png">
I made the recommended changes

2021-01-23 00:00 UTC, codingcodymiller approved these changes
🙌  🙌  🙌

2021-01-24 18:37 UTC, merged