Completed Array Manipulation 1 - Amelia Talkington
ameliatalkington/c0121-code-solutions pull request #42
Opened 2021-01-29 23:20 UTC by ameliatalkington

<img width="1015" alt="Screen Shot 2021-01-29 at 4 15 54 PM" src="https://user-images.githubusercontent.com/52344883/106337202-d7f39200-624d-11eb-8cfd-66fb4f9daaa8.png">

2021-01-29 23:27 UTC, codingcodymiller requested changes
Nice work so far! Please see my note

2021-01-29 23:27 UTC, codingcodymiller commented on array-manipulation-1/src/compact.js
> +      && array[i] !== '' && array[i] === array[i]) {
`if(!something)` will check if a value is falsy

2021-01-29 23:49 UTC, ameliatalkington commented
<img width="392" alt="Screen Shot 2021-01-29 at 4 48 48 PM" src="https://user-images.githubusercontent.com/52344883/106338811-fd829a80-6251-11eb-9253-81df17cac9b1.png">
<img width="990" alt="Screen Shot 2021-01-29 at 4 48 44 PM" src="https://user-images.githubusercontent.com/52344883/106338820-01aeb800-6252-11eb-80e6-19431b31c42d.png">

2021-01-30 00:50 UTC, thebearingedge approved these changes

2021-01-30 01:21 UTC, merged