Working with collections
ameliatalkington/c0121-code-solutions pull request #56
Opened 2021-02-04 17:41 UTC by ameliatalkington

<img width="456" alt="Screen Shot 2021-02-04 at 10 40 30 AM" src="https://user-images.githubusercontent.com/52344883/106932933-917eb700-66d5-11eb-8101-58a55f534674.png">

2021-02-04 19:15 UTC, thebearingedge requested changes
Great job, but some of the code could be clearer.

2021-02-04 19:15 UTC, thebearingedge commented on working-with-collections/main.js
> +}
This is the only part of your algorithm I'm having a hard time understanding. What is `arrayOfObjects`? Is it an array of card objects? Maybe the variable name could be improved.

Also, `objectOfCards`. Is it a single card object?

the inner `for ... in` loop can be omitted if `objectOfCards` is a card. You can access `card.rank` directly without a `for ... in`.

2021-02-04 23:43 UTC, ameliatalkington commented
<img width="706" alt="Screen Shot 2021-02-04 at 4 40 09 PM" src="https://user-images.githubusercontent.com/52344883/106969462-15519700-6708-11eb-90f1-22b750e5d431.png">

2021-02-05 15:34 UTC, thebearingedge requested changes
Much, much better. Good work! There is one more adjustment you can make that will improve the readability of your code.

2021-02-05 15:34 UTC, thebearingedge commented on working-with-collections/main.js
> +function calculateScore(shuffledDeck) {
This parameter name is misleading. It's not going to be the whole `shuffledDeck`, it's one of the player's `hand`s.

```js
function calculateScore(hand) { // 👀 

}
```

2021-02-05 19:07 UTC, ameliatalkington commented
<img width="310" alt="Screen Shot 2021-02-05 at 12 07 31 PM" src="https://user-images.githubusercontent.com/52344883/107077902-c01a9180-67aa-11eb-84da-ccdfea239703.png">

2021-02-05 19:36 UTC, thebearingedge approved these changes

2021-03-10 18:33 UTC, merged